// <auto-generated />
namespace Vidly_Most_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNameToMembsershipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNameToMembsershipType));
        
        string IMigrationMetadata.Id
        {
            get { return "201908101109211_AddNameToMembsershipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
